### ISSUE TITLE
Not detecting doombringer and ring of starless skies.

### ISSUE THREAD

**Issue by gdias1992** [aeon0/d4lf#111]
I am using this conf.

https://pastebin.com/HHsweAJV

**Comment by aeon0** [comment]
Could you make a screenshot how your unique look like? The problem is, the unique identification is done by reading the "golden" text. To properly find that text, the image is threshold for a certain color.

I thought I had a large enough threshold range for this color, but turns out, graphic settings are a lot more different than I anticipated.

Would be good to see if this problem goes into the same direction or is sth different.

**Comment by gdias1992** [comment]
![image](https://github.com/aeon0/d4lf/assets/25283876/93929f3e-e5e9-49b6-b4a5-1d0a8f4d83a7)
![image](https://github.com/aeon0/d4lf/assets/25283876/e820be8f-02d6-473a-925d-a73e0dece801)
![image](https://github.com/aeon0/d4lf/assets/25283876/8e7efd2b-b875-48bf-9fd3-41bf928ff4c7)
![image](https://github.com/aeon0/d4lf/assets/25283876/519aba00-569a-4240-830c-e06c46b8fefa)

**Comment by gdias1992** [comment]
Let me know if you need any other information.

Thank you for the open source filter!

**Comment by aeon0** [comment]
Hi, thanks for testing. I forgot to update the correct starless aspect description as it changed. Works now with latest commit: https://github.com/aeon0/d4lf/pull/114 in case you can run from python.
