### ISSUE TITLE
Only filter affixes

### ISSUE THREAD

**Issue by PolandDoge** [aeon0/d4lf#36]
Hi, is there any way to filter only the affixes without aspects?

**Comment by aeon0** [comment]
Copying info here to for completeness. It is currently possible by having a filter_aspects.yaml such as this:

```yaml
Aspects:
  # General
  - [accelerating_aspect, 99999]
```

The default behaviour for empty Aspects is to take any aspect. We can discuss if the default behaviour should be that it would not take any aspect in this case. But since that is not clearly a "issue" or "bug" I will close this one.
